### ISSUE TITLE
"Number" Type

### ISSUE THREAD

**Issue by noahrepublic** [KdudeDev/InfiniteMath#36]
Should be able to type(setmetatable({}, Number)) or something similar--

**Comment by KdudeDev** [comment]
I'm not experienced much with metatables, explain what this is and why its useful

**Comment by noahrepublic** [comment]
Often I am working with a mix of InfiniteMath numbers & normal integers, e.x, coins & last online

It is often difficult for me to remember which is which without scrolling back up, even my external editors' linter only can pick up it is a table. 

You can provide types on metatables to an extend.

e.x from my data module:

```

export type Keep = typeof(Keep.new({
	Data = DefaultKeep.Data,

	MetaData = DefaultMetaData,
	GlobalUpdates = DefaultGlobalUpdates,

	UserIds = DefaultKeep.UserIds,
}, {}))
```

**Comment by KdudeDev** [comment]
1.3.7 fixes this.
