### ISSUE TITLE
Add Number.ChangePrecision to change precision of numbers

### ISSUE THREAD

**Issue by foshesss** [KdudeDev/InfiniteMath#7]
Currently, the module will default to precision of '4' places. Example:
1.234billion
1,234,000,000 -- all numbers after the '4' are 0.

Users should have the opportunity to change the precision of all numbers by using a static method:
```lua
function Number.ChangePreicsion(n)
 -- change precision
end
```

**Comment by KdudeDev** [comment]
The function has been added, but it doesn't affect math yet

**Comment by KdudeDev** [comment]
I'm actually a bit confused on this function, from what I've seen the 1,234,000,000 example is false, and it'll go much further.

I tried printing IM.new(1234567890) and I got 1.234567890, 9 which is about 1.2 billion. I even printed the same number + 100 million and it gave me 1.33456789, 9, which is 1.3 billion.

Unless I'm misunderstanding the use of this function, this seems unneeded

**Comment by foshesss** [comment]
I think my original comment is out of date due to recent pushes, but I thought .ChangePrecision would allow people to change how precise of a number would be stored. 

For example:
Number.new(123,321,321) with a precision of 3 would return:
123 million (or 123,000,000), as opposed to the given argument.

This type of enhancement allows for somebody to store numbers with less precision, if they so desired.

**Comment by KdudeDev** [comment]
The way the module is written, the amount of decimals stored in the first number doesn't affect performance at all, so I don't see much use in this function.

Maybe we could add a decimal precision function for displaying numbers, like with GetSuffix and ScientificNotation. Right now ScientificNotation will display the entire number while GetSuffix is limited to 1 decimal, so a function for actual decimal precision could be added if people want it.
